# Netlify configuration for Metaverse Directory

[build]
  # Directory with the build output (auto-detected by plugin)
  # publish = ".next"
  
  # Build command (using pnpm since that's what Netlify detected)
  command = "pnpm run build"
  
  # Directory with the serverless functions
  functions = "netlify/functions"

[build.environment]
  # Node.js version for building
  NODE_VERSION = "20"
  
  # Next.js specific
  NEXT_TELEMETRY_DISABLED = "1"

# Headers configuration
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Redirects (if needed in the future)
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

# Next.js ISR support
[[plugins]]
  package = "@netlify/plugin-nextjs"

[plugins.inputs]
  # Disable Netlify Forms processing as we're not using them
  disableNetlifyForms = true

# Environment variables can be set in Netlify dashboard
# or in .env.local for local development